FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY  ./data-agent-management/target/spring-ai-alibaba-data-agent-management-1.0.0-SNAPSHOT.jar /app/app.jar

# 安装 Python
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# 安装 pandas（直接使用官方 wheel，不编译）
RUN pip3 install --no-cache-dir --upgrade pip \
    && pip3 install --no-cache-dir pandas

# 创建配置文件目录
RUN mkdir -p /app/config

EXPOSE 8065

# 启动命令，优先使用外部配置文件
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.config.location=classpath:application.yml,optional:file:/app/config/application.yml"]
